name: Slack Notification
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - uses: act10ns/slack@v1
        with:
          status: starting
          message: Starting Example Deployment...
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
        if: always()

      - name: Build example image
        id: build-image
        run: sleep 10s
        shell: bash
      
      - name: Deploy EU West
        id: deploy-eu-west
        run: sleep 10s
        shell: bash

      - name: Deploy US East
        id: deploy-us-east
        run: sleep 10s
        shell: bash

      - uses: act10ns/slack@v1
        with:
          message: Example Deployment Finished
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
        if: always()